import Head from 'next/head'
import Image from 'next/image'
import Popular from './r/popular'
import { prisma } from '../server/db/client'
import type { NextPage } from 'next'

type PostProps = {
  id: number;
  title: string;
  content: string;
  createdAt: Date;
}

type Props = {
  posts: PostProps[]
}

export async function getServerSideProps() {
  const posts = await prisma.post.findMany({
    include: {
      author: {
        select: { name: true, username: true },
      },
    },
    orderBy: [
      {
        createdAt: 'desc',
      }
    ]
  })
  return {
    props: {
      posts: JSON.parse(JSON.stringify(posts))
    }
  }
}

const Home: NextPage<Props> = ({posts}) => {
  return (

    // if user doesn't have a username, prompt the user to add a username
    <div>
      <Head>
        <title>Reddit - Dive into anything</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Popular posts={posts} />
    </div>
  )
}

export default Home