import Head from 'next/head'
import Image from 'next/image'
import Popular from './r/popular'
import { prisma } from '../server/db/client'
import { PostsListProps } from '../types/types'

export async function getServerSideProps() {
  const posts = await prisma.post.findMany({
    include: {
      author: {
        select: { name: true, username: true },
      },
    },
    orderBy: [
      {
        createdAt: 'desc',
      }
    ]
  })
  return {
    props: {
      posts: JSON.parse(JSON.stringify(posts))
    }
  }
}

export default function Home({posts}: PostsListProps) {
  return (
    <div>
      <Head>
        <title>Reddit - Dive into anything</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* // if user doesn't have a username, prompt the user to add a username */}
      <Popular posts={posts} />
    </div>
  )
}